# Generated by Django 3.1 on 2020-10-02 12:06

from django.db import migrations
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_postlike'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acc',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='postlike',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AddField(
            model_name='acc',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acc',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='postlike',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postlike',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
